### ISSUE TITLE
Assess for turning point

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#55]
> Because age is time-invariant, we cannot explore Research Question 2 using fixed-effects models. Therefore, for this particular research question we will conduct a random-effects model in which the effect of between subject variables (e.g., age) can be modelled. We will explore whether there is a turning point for age (age threshold) where an association between physical activity and sleep becomes evident.

Can this just be done visually? Or does a formal test need to occur?

**Comment by conig** [comment]
I think the test of the quadratic is the formal test. But we may need to mathematically extract the turning points from the regression equations and report them?

**Comment by tarensanders** [comment]
This protocol is crushing us.

I think if all we are reporting are the turning points then we just report the min (or max) value for age that has the highest/lowest association with sleep. There's no formal test - you just solve the regression equation for age.

**Comment by conig** [comment]
@tarensanders can you find the function phil used to automatically identify turning points?

**Comment by tarensanders** [comment]
Phil's code for this won't work because we have an interaction term and his was just for a simple quadratic. But, I think I know how to do this. I'll open a PR

**Comment by tarensanders** [comment]
OK I'm having a bit of trouble with this.

Using sleep as an example: since there's an interaction between the exposure (PA) and age, any turning point for age is dependent on the value of the exposure. I can calculate the value for PA and age that produces the highest (or lowest) value of sleep, but that doesn't really address the question...

The alternative is to extract the turning points for different points on age (i.e., the turning points from the plots), but that doesn't answer the question either.

We could calculate the value of age that gives the min/max of sleep for some given value of PA, but I don't think that really tells us "where an association between physical activity and sleep becomes evident".

Any ideas, @conig @mnoetel?

**Comment by conig** [comment]
Eesh. This isn't the most formal test, but might still answer the RQ. We use the delta method to estimate outcomes for combos of age and predictors to determine when a small increase in the predictor (e.g., d = .2) results in a statistically significant increase in the outcome. Could then plot the grid with geom_tile. Or we could just be in a violation on this one.

```
> expand.grid(age = seq(10,80, by = 5), scale_predictor = seq(-4,4, by = .2)) |> nrow()
[1] 615
```
Result might look something like this:
![image](https://user-images.githubusercontent.com/12742211/228117683-aa989621-c182-4c73-8498-ba1e16c3aebc.png)

**Comment by tarensanders** [comment]
Yeah, that makes a ton of sense.
